name: rapids-25.10
channels:
  - conda-forge
  - rapidsai
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - adwaita-icon-theme=49.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.0
  - aiosignal=1.4.0
  - alembic=1.17.0
  - alsa-lib=1.2.14
  - anyio=4.11.0
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attr=2.5.2
  - attrs=25.4.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.22.0
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - beautifulsoup4=4.14.2
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - bokeh=3.8.0
  - branca=0.8.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.21.3
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=6.2.1
  - cairo=1.18.4
  - catboost=1.2.8
  - certifi=2025.11.12
  - cffi=2.0.0
  - charls=2.4.2
  - charset-normalizer=3.4.4
  - click=8.3.0
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorcet=3.1.0
  - colorlog=6.10.1
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.13.9
  - cucim=25.10.00
  - cuda-bindings=12.9.3
  - cuda-cccl_linux-64=12.9.27
  - cuda-core=0.3.2
  - cuda-crt-dev_linux-64=12.9.86
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.9.79
  - cuda-cudart-dev=12.9.79
  - cuda-cudart-dev_linux-64=12.9.79
  - cuda-cudart-static=12.9.79
  - cuda-cudart-static_linux-64=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.9.79
  - cuda-nvcc-dev_linux-64=12.9.86
  - cuda-nvcc-impl=12.9.86
  - cuda-nvcc-tools=12.9.86
  - cuda-nvdisasm=12.9.88
  - cuda-nvrtc=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-nvvm-dev_linux-64=12.9.86
  - cuda-nvvm-impl=12.9.86
  - cuda-nvvm-tools=12.9.86
  - cuda-pathfinder=1.3.1
  - cuda-profiler-api=12.9.79
  - cuda-python=12.9.3
  - cuda-version=12.9
  - cudf=25.10.00
  - cudf-polars=25.10.00
  - cudf_kafka=25.10.00
  - cudnn=9.13.1.26
  - cugraph=25.10.01
  - cuml=25.10.00
  - cupy=13.6.0
  - cupy-core=13.6.0
  - custreamz=25.10.00
  - cuvs=25.10.00
  - cuxfilter=25.10.00
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.0.1
  - dask=2025.9.1
  - dask-core=2025.9.1
  - dask-cuda=25.10.00
  - dask-cudf=25.10.00
  - datashader=0.18.2
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distributed=2025.9.1
  - distributed-ucxx=0.46.00
  - dlpack=0.8
  - einops=0.8.1
  - epoxy=1.5.10
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fastrlock=0.8.3
  - ffmpeg=8.0.0
  - filelock=3.20.0
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.16
  - frozenlist=1.7.0
  - fsspec=2025.9.0
  - gdk-pixbuf=2.44.4
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.14.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glib-tools=2.86.0
  - glog=0.7.1
  - glslang=16.1.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - graphviz=13.1.2
  - greenlet=3.2.4
  - gtk3=3.24.43
  - gts=0.7.6
  - h2=4.3.0
  - harfbuzz=12.1.0
  - hicolor-icon-theme=0.17
  - holoviews=1.21.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imagecodecs=2025.8.2
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - intel-gmmlib=22.8.2
  - intel-media-driver=25.3.4
  - ipykernel=7.0.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json-c=0.18
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-server-proxy=4.4.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_widgets=3.0.15
  - jxrlib=1.1
  - kaldi=5.5.1172
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lark=1.3.0
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - level-zero=1.26.1
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarchive=3.8.2
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.76
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.9.1.4
  - libcublas-dev=12.9.1.4
  - libcucim=25.10.00
  - libcudf=25.10.00
  - libcudf_kafka=25.10.00
  - libcudnn=9.13.1.26
  - libcudnn-dev=9.13.1.26
  - libcudss=0.7.0.20
  - libcufft=11.4.1.4
  - libcufile=1.14.1.1
  - libcufile-dev=1.14.1.1
  - libcugraph=25.10.01
  - libcugraph_etl=25.10.01
  - libcuml=25.10.00
  - libcumlprims=25.10.00
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurl=8.14.1
  - libcusolver=11.7.5.82
  - libcusolver-dev=11.7.5.82
  - libcusparse=12.5.10.65
  - libcusparse-dev=12.5.10.65
  - libcuvs=25.10.00
  - libde265=1.0.15
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libegl-devel=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgcrypt-lib=1.11.1
  - libgd=2.3.3
  - libgdal-core=3.11.4
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libgl-devel=1.7.0
  - libglib=2.86.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libglx-devel=1.7.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgpg-error=1.55
  - libgrpc=1.73.1
  - libheif=1.19.7
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - libkvikio=25.10.00
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblightgbm=4.6.0
  - liblzma=5.8.1
  - libmagma=2.9.0
  - libmagma_sparse=2.9.0
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libnl=3.11.0
  - libnpp=12.4.1.87
  - libnsl=2.0.1
  - libntlm=1.8
  - libnuma=2.0.18
  - libnvcomp=5.0.0.6
  - libnvcomp-dev=5.0.0.6
  - libnvjitlink=12.9.86
  - libnvjpeg=12.4.0.76
  - libnvptxcompiler-dev=12.9.86
  - libnvptxcompiler-dev_linux-64=12.9.86
  - libogg=1.3.5
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-intel-npu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libparquet=21.0.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libraft=25.10.00
  - libraft-headers=25.10.00
  - libraft-headers-only=25.10.00
  - librdkafka=2.8.0
  - libre2-11=2025.08.12
  - librmm=25.10.00
  - librsvg=2.60.0
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=257.9
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libtorch=2.8.0
  - libucxx=0.46.00
  - libudev1=257.9
  - libunwind=1.8.3
  - liburing=2.12
  - libusb=1.0.29
  - libutf8proc=2.11.0
  - libuuid=2.41.2
  - libuv=1.51.0
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.14.1
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=3.0.5
  - libxkbcommon=1.12.3
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libxml2-devel=2.15.0
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lightgbm=4.6.0
  - linkify-it-py=2.0.3
  - llvm-openmp=21.1.3
  - llvmlite=0.44.0
  - locket=1.0.0
  - lz4=4.4.4
  - lz4-c=1.10.0
  - lzo=2.10
  - mako=1.3.10
  - mapclassify=2.10.0
  - markdown=3.9
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - minizip=4.0.10
  - mistune=3.1.4
  - mkl=2024.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - multidict=6.6.3
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - muparser=2.3.5
  - narwhals=2.8.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nccl=2.28.9.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nlohmann_json=3.12.0
  - nodejs=24.9.0
  - numba=0.61.2
  - numba-cuda=0.19.1
  - numpy=2.2.6
  - nvidia-ml-py=13.580.82
  - nvtx=0.2.13
  - nx-cugraph=25.10.00
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openfst=1.8.4
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - optree=0.17.0
  - optuna=3.6.1
  - orc=2.2.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - panel=1.8.2
  - pango=1.56.4
  - param=2.2.1
  - parso=0.8.5
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - plotly=6.3.1
  - polars=1.32.3
  - polars-default=1.32.3
  - proj=9.7.0
  - prometheus-cpp=1.3.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py-xgboost=3.0.5
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pyct=0.6.0
  - pygments=2.19.2
  - pylibcudf=25.10.00
  - pylibcugraph=25.10.01
  - pylibraft=25.10.00
  - pyogrio=0.11.1
  - pyparsing=3.2.5
  - pyproj=3.7.2
  - pysocks=1.7.1
  - python=3.13.9
  - python-confluent-kafka=2.8.0
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.13.9
  - python-graphviz=0.21
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytorch=2.8.0
  - pytz=2025.2
  - pyviz_comms=3.0.6
  - pywavelets=1.9.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - raft-dask=25.10.00
  - rapids=25.10.00
  - rapids-dask-dependency=25.10.00
  - rapids-logger=0.1.1
  - rapids-xgboost=25.10.00
  - rav1e=0.7.1
  - rdma-core=59.0
  - re2=2025.08.12
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.2.0
  - rmm=25.10.00
  - rpds-py=0.27.1
  - s2n=1.5.26
  - scikit-image=0.24.0
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - sdl2=2.32.56
  - sdl3=3.2.26
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shaderc=2025.4
  - shapely=2.1.2
  - simpervisor=1.0.0
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - spirv-tools=2025.4
  - sqlalchemy=2.0.44
  - sqlite=3.50.4
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - streamz=0.6.4
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2021.13.0
  - tblib=3.1.0
  - termcolor=3.2.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tifffile=2025.10.4
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.3.0
  - toolz=1.0.0
  - torchaudio=2.8.0
  - torchcodec=0.8.1
  - torchvision=0.24.0
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - treelite=4.4.1
  - triton=3.4.0
  - types-python-dateutil=2.9.0.20251008
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uc-micro-py=1.0.3
  - ucx=1.19.0
  - ucxx=0.46.00
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - wayland=1.24.0
  - wayland-protocols=1.46
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - widgetsnbextension=4.0.14
  - x264=1!164.3095
  - x265=3.5
  - xarray=2025.10.1
  - xerces-c=3.2.5
  - xgboost=3.0.5
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - et-xmlfile==2.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google==3.0.0
      - lightning-utilities==0.15.2
      - openpyxl==3.1.5
      - protobuf==6.33.0
      - pydantic==2.12.2
      - pydantic-core==2.41.4
      - pytabkit==1.6.1
      - python-dotenv==1.1.1
      - pytorch-lightning==2.5.5
      - sentry-sdk==2.42.0
      - smmap==5.0.2
      - torchmetrics==1.8.2
      - typing-inspection==0.4.2
      - wandb==0.22.2
prefix: /home/hanse/miniconda3/envs/rapids-25.10
